version: "3.8"

services:
  comfyui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: comfyui
    ports:
      - "3000:8188"
    volumes:
      - comfyui-data:/app
    restart: always
    labels:
      - coolify.enable=true
      - coolify.application.domain=comfy.cadeauxfleur.com
      - traefik.enable=true
      - traefik.http.routers.comfyui.rule=Host(`comfy.cadeauxfleur.com`)
      - traefik.http.routers.comfyui.entrypoints=websecure
      - traefik.http.routers.comfyui.tls.certresolver=letsencrypt
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8188"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  comfyui-data:
